services:
  postgres:
    image: postgres:16
    container_name: olist_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: olist
    ports:
      - "5432:5432"
    volumes:
      - olist_pgdata:/var/lib/postgresql/data

  airflow_postgres:
    image: postgres:16
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5434:5432"
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data

  airflow_init:
    image: apache/airflow:2.10.5
    container_name: airflow_init
    depends_on:
      - airflow_postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/opt/airflow/project
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username airflow
      --password airflow
      --firstname Airflow
      --lastname Admin
      --role Admin
      --email airflow@example.com || true
      "

  airflow_webserver:
    image: apache/airflow:2.10.5
    container_name: airflow_webserver
    depends_on:
      airflow_init:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      DB_URL: postgresql://postgres:postgres@postgres:5432/olist
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/opt/airflow/project
    ports:
      - "8080:8080"
    command: webserver

  airflow_scheduler:
    image: apache/airflow:2.10.5
    container_name: airflow_scheduler
    depends_on:
      airflow_webserver:
        condition: service_started
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      DB_URL: postgresql://postgres:postgres@postgres:5432/olist
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/opt/airflow/project
    command: scheduler

volumes:
  olist_pgdata:
  airflow_pgdata: