services:
  postgres:
    image: postgres:16
    container_name: olist_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: olist
    ports:
      - "5432:5432"
    volumes:
      - olist_pgdata:/var/lib/postgresql/data

volumes:
  olist_pgdata:
